colors:
  text: '#000000'
  custom_timestamp_author_light_color: [51, 51, 51]
  custom_timestamp_author_dark_color: [204, 204, 204]
  custom_location_light_color: [51, 51, 51]
  custom_location_dark_color: [204, 204, 204]
fonts:
  family: Gotham
  weight: medium
  size_ratio: 0.01
  sizes:
    exif: 0.011
    timestamp_author: 0.011
    camera_lens: 0.011
    location: 0.011
layout:
  expand_canvas:
    enabled: true
    top: 0.03
    bottom: 0.1
    left: 0.015
    right: 0.015
  padding:
    top: 0.02
    bottom: 0.02
    left: 0.02
    right: 0.02
  info_position:
    exif:
      position: "bottom-left"
      alignment: "left"
      margin_top: 0
      margin_bottom: 0.02
      margin_left: 0
      margin_right: 0
    timestamp_author:
      relative_to: "exif"
      relative_position: "below"
      alignment: "left"
      relative_margin: 0.01
    camera_lens:
      position: "bottom-right"
      alignment: "right"
      margin_top: 0
      margin_bottom: 0.02
      margin_left: 0
      margin_right: 0
    location:
      relative_to: "camera_lens"
      relative_position: "below"
      alignment: "right"
      relative_margin: 0.01
logo:
  enabled: false
name: 宝丽来风格 Polaroid
